{
 "title": "Fluentd-进程监控",
 "description": "Fluentd-进程监控",
 "tags": [ "k8s-log" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "query_result(sum by(scrape_job) (prometheus_target_sync_length_seconds_count{scrape_job=~\".*pods\",scrape_job != \"bj-prehwhbbj4-1-kubernetes-pods\"}))"
   },
   {
    "name": "fluentd_pod_name",
    "query": "label_values({k8s_app=\"fluentd-logging\",job=\"$cluster\"},kubernetes_pod_name)"
   },
   { "name": "Interval", "query": "1m,2m,10m,2h" }
  ]
 },
 "panels": [
  { "title": "ERROR日志监控【Cluster】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ERROR Log Records",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_error_log_records{cluster=\"$cluster\"}[$Interval]))",
     "legendFormat": "cluster"
    }
   ]
  },
  {
   "title": "Fluentd Process Died",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_process_died_records{cluster=\"$cluster\"}[$Interval]))",
     "legendFormat": "cluster"
    }
   ]
  },
  {
   "title": "Kafka Connection Timeout",
   "type": "graph",
   "description": "kafka timeout records",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_kafka_timeout_records{cluster=\"$cluster\"}[$Interval]))",
     "legendFormat": "cluster"
    }
   ]
  },
  {
   "title": "Kafka Write Failed",
   "type": "graph",
   "description": "kafka timeout records",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_write_kafka_failed_records{cluster=\"$cluster\"}[$Interval]))",
     "legendFormat": "cluster"
    }
   ]
  },
  { "title": "ERROR日志监控【Fluentd Pod】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "ERROR Log Records",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_error_log_records{cluster=\"$cluster\",kubernetes_pod_name =~\"$fluentd_pod_name\"}[$Interval])) by(instance,kubernetes_pod_name,fluentd_process)",
     "legendFormat": "{{instance}} | {{kubernetes_pod_name}} | {{fluentd_process}}"
    }
   ]
  },
  {
   "title": "Fluentd Process Died",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_process_died_records{cluster=\"$cluster\",kubernetes_pod_name =~\"$fluentd_pod_name\"}[$Interval])) by(instance,kubernetes_pod_name,fluentd_process)",
     "legendFormat": "{{instance}} | {{kubernetes_pod_name}} | {{fluentd_process}}"
    }
   ]
  },
  {
   "title": "Kafka Connection Timeout",
   "type": "graph",
   "description": "kafka timeout records",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_kafka_timeout_records{cluster=\"$cluster\",kubernetes_pod_name =~\"$fluentd_pod_name\"}[$Interval])) by(instance,kubernetes_pod_name,fluentd_process)",
     "legendFormat": "{{instance}} | {{kubernetes_pod_name}} | {{fluentd_process}}"
    }
   ]
  },
  {
   "title": "Kafka Write Failed",
   "type": "graph",
   "description": "kafka timeout records",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_write_kafka_failed_records{cluster=\"$cluster\",kubernetes_pod_name =~\"$fluentd_pod_name\"}[$Interval])) by(instance,kubernetes_pod_name,fluentd_process)",
     "legendFormat": "{{instance}} | {{kubernetes_pod_name}} | {{fluentd_process}}"
    }
   ]
  },
  {
   "title": "WARN日志监控【Cluster】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slow Flush 2 Kafka (WARN)",
     "type": "graph",
     "description": "kafka timeout records",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_slow_flush_records{cluster=\"$cluster\"}[$Interval]))",
       "legendFormat": "cluster"
      }
     ]
    },
    {
     "title": "Concat Docker Plugin Timeout (WARN)",
     "type": "graph",
     "description": "kafka timeout records",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_concat_timeout_records{cluster=\"$cluster\"}[$Interval]))",
       "legendFormat": "cluster"
      }
     ]
    }
   ]
  },
  {
   "title": "WARN日志监控【Fluentd Pod】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slow Flush 2 Kafka (WARN)",
     "type": "graph",
     "description": "kafka timeout records",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_slow_flush_records{cluster=\"$cluster\",kubernetes_pod_name =~\"$fluentd_pod_name\"}[$Interval])) by(instance,kubernetes_pod_name,fluentd_process)",
       "legendFormat": "{{instance}} | {{kubernetes_pod_name}} | {{fluentd_process}}"
      }
     ]
    },
    {
     "title": "Concat Docker Plugin Timeout (WARN)",
     "type": "graph",
     "description": "kafka timeout records",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_concat_timeout_records{cluster=\"$cluster\",kubernetes_pod_name =~\"$fluentd_pod_name\"}[$Interval])) by(instance,kubernetes_pod_name,fluentd_process)",
       "legendFormat": "{{instance}} | {{kubernetes_pod_name}} | {{fluentd_process}}"
      }
     ]
    }
   ]
  }
 ]
}