{
 "title": "Fluentd-采集监控",
 "tags": [ "k8s-log" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "query_result(sum by(scrape_job) (prometheus_target_sync_length_seconds_count{scrape_cluster=~\".*pods\",scrape_job != \"bj-prehwhbbj4-1-kubernetes-pods\"}))"
   },
   {
    "name": "fluentd_pod_name",
    "label": "fluentd_pod_name",
    "query": "query_result(count by (kubernetes_pod_name) (fluentd_flowcounter_output_emit_records{k8s_app=\"fluentd-logging\",cluster=\"$cluster\"}) )"
   },
   {
    "name": "log_namespace",
    "label": "log_namespace",
    "query": "query_result(count by (log_namespace) (fluentd_flowcounter_output_emit_records{k8s_app=\"fluentd-logging\",cluster=\"$cluster\",kubernetes_pod_name=~\"$fluentd_pod_name\"}))"
   },
   {
    "name": "log_cname",
    "query": "query_result(count by(log_cname) (fluentd_flowcounter_output_emit_records{k8s_app=\"fluentd-logging\",cluster=\"$cluster\",kubernetes_pod_name=~\"$fluentd_pod_name\",log_namespace=~\"$log_namespace\"}))"
   },
   { "name": "Interval", "query": "1m,2m,10m,2h" }
  ]
 },
 "panels": [
  {
   "title": "Output Buffer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fluentd Buffer 大小 (bytes)",
     "type": "singlestat",
     "description": "fluentd_output_status_buffer_total_bytes",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
     "format": "decbytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (fluentd_output_status_buffer_total_bytes{cluster=\"$cluster\",kubernetes_pod_name =~ \"$fluentd_pod_name\"})"
      }
     ]
    },
    {
     "title": "Fluentd Buffer Queue长度",
     "type": "singlestat",
     "description": "fluentd_output_status_buffer_queue_length",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (fluentd_output_status_buffer_queue_length{cluster=\"$cluster\",kubernetes_pod_name =~ \"$fluentd_pod_name\"})"
      }
     ]
    },
    {
     "title": "Fluentd Flush 2 Queue 重试次数",
     "type": "singlestat",
     "description": "fluentd_output_status_retry_count",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (fluentd_output_status_retry_count{cluster=\"$cluster\",kubernetes_pod_name =~ \"$fluentd_pod_name\"})"
      }
     ]
    },
    {
     "title": "Fluentd Buffer 大小 (map+queue) (bytes)",
     "type": "graph",
     "description": "fluentd_output_status_buffer_total_bytes",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum (fluentd_output_status_buffer_total_bytes{cluster=\"$cluster\",kubernetes_pod_name =~ \"$fluentd_pod_name\"}) by(instance,kubernetes_pod_name,name)",
       "legendFormat": "{{instance}} | {{kubernetes_pod_name}} | {{name}}"
      }
     ]
    },
    {
     "title": "Fluentd Buffer Queue 长度",
     "type": "graph",
     "description": "fluentd_output_status_buffer_queue_length",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(fluentd_output_status_buffer_queue_length{cluster=\"$cluster\",kubernetes_pod_name =~ \"$fluentd_pod_name\"}) by (instance,kubernetes_pod_name,name)",
       "legendFormat": "{{instance}} | {{kubernetes_pod_name}} | {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Output Emit【Cluster】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "output emit records/s",
     "type": "singlestat",
     "description": "fluentd_flowcounter_output_emit_records",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(rate(fluentd_flowcounter_output_emit_records{cluster=\"$cluster\",kubernetes_pod_name =~ \"$fluentd_pod_name\", log_namespace =~ \"$log_namespace\",log_cname =~ \"$log_cname\"}[$Interval]))"
      }
     ]
    },
    {
     "title": "output emit bytes/s",
     "type": "singlestat",
     "description": "fluentd_flowcounter_output_emit_bytes",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 2 },
     "format": "decbytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(rate(fluentd_flowcounter_output_emit_bytes{cluster=\"$cluster\",kubernetes_pod_name =~ \"$fluentd_pod_name\", log_namespace =~ \"$log_namespace\",log_cname =~ \"$log_cname\"}[$Interval]))"
      }
     ]
    },
    {
     "title": "output emit raw log bytes/s",
     "type": "singlestat",
     "description": "fluentd_flowcounter_output_emit_raw_log_bytes",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 2 },
     "format": "decbytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(rate(fluentd_flowcounter_output_emit_raw_log_bytes{cluster=\"$cluster\",kubernetes_pod_name =~ \"$fluentd_pod_name\", log_namespace =~ \"$log_namespace\",log_cname =~ \"$log_cname\"}[$Interval]))"
      }
     ]
    },
    {
     "title": "output emit records/s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "  sum(rate(fluentd_flowcounter_output_emit_records{cluster=\"$cluster\",kubernetes_pod_name =~ \"$fluentd_pod_name\", log_namespace =~ \"$log_namespace\", log_cname =~ \"$log_cname\"}[$Interval]))",
       "legendFormat": "Cluster-Total"
      }
     ]
    },
    {
     "title": "output emit bytes/s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "  sum(rate(fluentd_flowcounter_output_emit_bytes{cluster=\"$cluster\",kubernetes_pod_name =~ \"$fluentd_pod_name\", log_namespace =~ \"$log_namespace\",log_cname =~ \"$log_cname\"}[$Interval]))",
       "legendFormat": "Cluster-Total"
      }
     ]
    },
    {
     "title": "output emit raw log bytes/s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "  sum(rate(fluentd_flowcounter_output_emit_raw_log_bytes{cluster=\"$cluster\",kubernetes_pod_name =~ \"$fluentd_pod_name\", log_namespace =~ \"$log_namespace\", log_cname =~ \"$log_cname\"}[$Interval]))",
       "legendFormat": "Cluster-Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Output Emit【Node】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "output emit records/s",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " sum(rate(fluentd_flowcounter_output_emit_records{cluster=\"$cluster\",kubernetes_pod_name =~ \"$fluentd_pod_name\", log_namespace =~ \"$log_namespace\",log_cname =~ \"$log_cname\"}[$Interval])) by(kubernetes_pod_name)",
       "legendFormat": " {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "output emit bytes/s",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": " sum(rate(fluentd_flowcounter_output_emit_bytes{cluster=\"$cluster\",kubernetes_pod_name =~ \"$fluentd_pod_name\", log_namespace =~ \"$log_namespace\", log_cname =~ \"$log_cname\"}[$Interval])) by(kubernetes_pod_name)",
       "legendFormat": " {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "output emit raw log bytes/s",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": " sum(rate(fluentd_flowcounter_output_emit_raw_log_bytes{cluster=\"$cluster\",kubernetes_pod_name =~ \"$fluentd_pod_name\", log_namespace =~ \"$log_namespace\",log_cname =~ \"$log_cname\"}[$Interval])) by(kubernetes_pod_name)",
       "legendFormat": " {{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Output Emit【Namespace+Container】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "output emit records/s",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " sum(rate(fluentd_flowcounter_output_emit_records{cluster=\"$cluster\",kubernetes_pod_name =~ \"$fluentd_pod_name\", log_namespace =~ \"$log_namespace\", log_cname =~ \"$log_cname\"}[$Interval])) by (log_namespace, log_cname)",
       "legendFormat": "ns = {{log_namespace}} | cn = {{log_cname}}"
      }
     ]
    },
    {
     "title": "output emit bytes/s",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": " sum(rate(fluentd_flowcounter_output_emit_bytes{cluster=\"$cluster\",kubernetes_pod_name =~ \"$fluentd_pod_name\", log_namespace =~ \"$log_namespace\", log_cname =~ \"$log_cname\"}[$Interval])) by (log_namespace, log_cname)",
       "legendFormat": "ns = {{log_namespace}}  | cn = {{log_cname}}"
      }
     ]
    },
    {
     "title": "【fluentd】 output emit bytes/s",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_flowcounter_output_emit_bytes{cluster=\"$cluster\",kubernetes_pod_name =~ \"$fluentd_pod_name\", log_namespace =~ \"$log_namespace\", log_cname =~ \"$log_cname\"}[$Interval])) by (kubernetes_pod_name, log_cname)",
       "legendFormat": "fluent = {{kubernetes_pod_name}}  | cn = {{log_cname}}"
      }
     ]
    },
    {
     "title": "output emit raw log bytes/s",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": " sum(rate(fluentd_flowcounter_output_emit_raw_log_bytes{cluster=\"$cluster\",kubernetes_pod_name =~ \"$fluentd_pod_name\", log_namespace =~ \"$log_namespace\", log_cname =~ \"$log_cname\"}[$Interval])) by (log_namespace, log_cname)",
       "legendFormat": "ns = {{log_namespace}} | cn = {{log_cname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Input Emit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "input emit records/s",
     "type": "singlestat",
     "description": "fluentd_flowcounter_output_emit_records",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "  sum(rate(fluentd_input_records{cluster=\"$cluster\",kubernetes_pod_name =~ \"$fluentd_pod_name\"}[$Interval]))"
      }
     ]
    },
    {
     "title": "input emit records/s",
     "type": "graph",
     "description": "fluentd_input_records",
     "gridPos": { "h": 8, "w": 10, "x": 4, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "  sum(rate(fluentd_input_records{cluster=\"$cluster\",kubernetes_pod_name =~ \"$fluentd_pod_name\"}[$Interval]))",
       "legendFormat": "Cluster-Total"
      }
     ]
    },
    {
     "title": "input emit records/s",
     "type": "graph",
     "description": "fluentd_input_records",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "  sum(rate(fluentd_input_records{cluster=\"$cluster\",kubernetes_pod_name =~ \"$fluentd_pod_name\"}[$Interval])) by (kubernetes_pod_name)",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Error Monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fluentd 日志采集error次数 (30s)",
     "type": "graph",
     "description": "fluentd_output_status_num_errors",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_num_errors{cluster=\"$cluster\",kubernetes_pod_name =~ \"$fluentd_pod_name\"}[$Interval])) by (kubernetes_pod_name)",
       "legendFormat": " {{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Fluentd 日志裁剪次数",
     "type": "graph",
     "description": "fluentd_output_status_retry_count",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_prune_log_records{cluster=\"$cluster\",kubernetes_pod_name =~ \"$fluentd_pod_name\"}[$Interval])) by (kubernetes_pod_name)",
       "legendFormat": "cluster"
      }
     ]
    }
   ]
  }
 ]
}