{
 "title": "Golang进程监控",
 "description": "Golang进程监控",
 "tags": [ "Golang Process" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(go_goroutines{job=\"golang-process-metrics\"},cluster)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(go_goroutines{job=\"golang-process-metrics\", cluster=\"$cluster\"},instance)"
   },
   { "name": "Interval", "query": "1m,2m,10m,2h" }
  ]
 },
 "panels": [
  { "title": "Golang info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Go version",
   "type": "table",
   "description": "Golang SDK version",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(go_info{job=~\"golang-process-metrics\",cluster=~\"$cluster\", instance=~\"$node\"}) by (cluster, instance, version)"
    }
   ]
  },
  {
   "title": "Process starttime",
   "type": "table",
   "description": "Start time of the process since unix epoch in seconds",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(ceil(process_start_time_seconds{job=~\"golang-process-metrics\",cluster=~\"$cluster\", instance=~\"$node\"})*1000) by (cluster, instance)"
    }
   ]
  },
  { "title": "Process info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Process Goroutine",
   "type": "graph",
   "description": "Number of Goroutine",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=~\"golang-process-metrics\",cluster=~\"$cluster\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process thread",
   "type": "graph",
   "description": "Number of OS threads created.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{job=~\"golang-process-metrics\",cluster=~\"$cluster\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process open fds",
   "type": "graph",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=~\"golang-process-metrics\",cluster=~\"$cluster\", instance=~\"$node\"}  ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Per second GC count",
   "type": "graph",
   "description": "Per Second GC count",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_count{job=~\"golang-process-metrics\",cluster=~\"$cluster\", instance=~\"$node\"}[$Interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average GC time",
   "type": "graph",
   "description": "Average GC time consuming",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds_sum{job=~\"golang-process-metrics\",cluster=~\"$cluster\", instance=~\"$node\"} / go_gc_duration_seconds_count{job=~\"golang-process-metrics\",cluster=~\"$cluster\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process memory",
   "type": "graph",
   "description": "Resident memory size in bytes",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"golang-process-metrics\",cluster=~\"$cluster\", instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory mallocs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memstats",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{job=~\"golang-process-metrics\",cluster=~\"$cluster\", instance=~\"$node\"}",
       "legendFormat": "{{instance}}-alloc"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job=~\"golang-process-metrics\",cluster=~\"$cluster\", instance=~\"$node\"}",
       "legendFormat": "{{instance}}-heap-inuse"
      }
     ]
    },
    {
     "title": "Memstats gc sys bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "expr": " go_memstats_gc_sys_bytes{job=~\"golang-process-metrics\",cluster=~\"$cluster\", instance=~\"$node\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memstats buck hash sys bytes",
     "type": "graph",
     "description": "Number of bytes used by the profiling bucket hash table",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "expr": " go_memstats_buck_hash_sys_bytes{job=~\"golang-process-metrics\",cluster=~\"$cluster\", instance=~\"$node\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memstats heap idle bytes",
     "type": "graph",
     "description": "Number of heap bytes waiting to be used.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "expr": " go_memstats_heap_idle_bytes{job=~\"golang-process-metrics\",cluster=~\"$cluster\", instance=~\"$node\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memstats heap inuse bytes",
     "type": "graph",
     "description": "Number of heap bytes that are in use.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "expr": " go_memstats_heap_inuse_bytes{job=~\"golang-process-metrics\",cluster=~\"$cluster\", instance=~\"$node\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memstats heap alloc bytes",
     "type": "graph",
     "description": "Number of heap bytes allocated and still in use",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "expr": " go_memstats_heap_alloc_bytes{job=~\"golang-process-metrics\",cluster=~\"$cluster\", instance=~\"$node\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}