{
 "title": "Matrix - batch API服务监控",
 "description": "Matrix - batch API服务监控",
 "tags": [ "matrix-batch" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(matrix_batch_http_request_latency_count{job=\"matrix-batch-metrics\"}, cluster)"
   },
   {
    "name": "node",
    "label": "node",
    "query": "label_values(matrix_batch_http_request_latency_count{job=\"matrix-batch-metrics\", cluster=~\"$cluster\"}, instance)"
   },
   {
    "name": "method",
    "label": "method",
    "query": "label_values(matrix_batch_http_request_latency_count{job=\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\"}, method)"
   },
   {
    "name": "path",
    "label": "path",
    "query": "label_values(matrix_batch_http_request_latency_count{job=\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\", method=~\"$method\"}, path)"
   },
   {
    "name": "status",
    "label": "status",
    "query": "label_values(matrix_batch_http_request_latency_count{job=\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\", method=~\"$method\", path=~\"$path\"}, status_code)"
   },
   { "name": "Interval", "query": "1m,2m,10m,2h" }
  ]
 },
 "panels": [
  {
   "title": "总览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "请求总数",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(matrix_batch_http_request_latency_count{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"$method\",path=~\"$path\",status_code=~\"$status\"}[$__range]))"
      }
     ]
    },
    {
     "title": "错误数",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(matrix_batch_http_request_latency_count{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"$method\",path=~\"$path\"}[$__range:])) \n-\nsum(increase(matrix_batch_http_request_latency_count{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"$method\",path=~\"$path\",status_code=\"200\"}[$__range:]))"
      }
     ]
    },
    {
     "title": "慢请求数",
     "type": "singlestat",
     "description": "请求响应时间超过50ms",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase((matrix_batch_http_request_latency_bucket{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"$method\",path=~\"$path\",status_code=~\"$status\",le=\"+Inf\"}\n- ignoring(le)\nmatrix_batch_http_request_latency_bucket{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"$method\",path=~\"$path\",status_code=~\"$status\",le=\"50\"})[$__range:]))"
      }
     ]
    },
    {
     "title": "大数据任务请求数",
     "type": "singlestat",
     "description": "大数据创建调度任务请求数",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(matrix_batch_http_request_bigdata{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"$method\",path=~\"$path\",status_code=~\"$status\"}[$__range]))"
      }
     ]
    },
    {
     "title": "成功率",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(matrix_batch_http_request_latency_count{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"$method\",path=~\"$path\",status_code=\"200\"}[$__range:]))\n/ \nsum(increase(matrix_batch_http_request_latency_count{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"$method\",path=~\"$path\"}[$__range:]))"
      }
     ]
    },
    {
     "title": "平均响应时间",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(matrix_batch_http_request_latency_sum{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"$method\",path=~\"$path\",status_code=~\"$status\"}[$__range:])) \n/\nsum(increase(matrix_batch_http_request_latency_count{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"$method\",path=~\"$path\",status_code=~\"$status\"}[$__range:]))"
      }
     ]
    },
    {
     "title": "请求 QPS",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(matrix_batch_http_request_latency_count{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"$method\",path=~\"$path\",status_code=~\"$status\"}[$Interval]))",
       "legendFormat": "QPS"
      }
     ]
    },
    {
     "title": "请求分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(matrix_batch_http_request_latency_count{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"$method\",path=~\"$path\",status_code=~\"200\"}[$__range:])) ",
       "legendFormat": "Success"
      },
      {
       "expr": "sum(increase(matrix_batch_http_request_latency_count{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"$method\",path=~\"$path\",status_code=~\"$status\"}[$__range:])) \n-\nsum(increase(matrix_batch_http_request_latency_count{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"$method\",path=~\"$path\",status_code=\"200\"}[$__range:]))",
       "legendFormat": "Failed"
      }
     ]
    },
    {
     "title": "大数据任务 请求分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(matrix_batch_http_request_bigdata{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"POST\",path=~\".*manually_trigger\",status_code=~\"$status\"}[$__range]))",
       "legendFormat": "Create Job"
      },
      {
       "expr": "sum(increase(matrix_batch_http_request_bigdata{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"POST\",path=~\".*info\",status_code=~\"$status\"}[$__range]))",
       "legendFormat": "Get Jobs Info"
      },
      {
       "expr": "sum(increase(matrix_batch_http_request_bigdata{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"DELETE\",path=~\".*/job/.*\",status_code=~\"$status\"}[$__range]))",
       "legendFormat": "Delete Job"
      }
     ]
    }
   ]
  },
  { "title": "SLA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "SLA总体情况",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(matrix_batch_http_request_latency_count{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"$method\",path=~\"$path\",status_code=\"200\"}[$Interval]))\n/ \nsum(rate(matrix_batch_http_request_latency_count{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"$method\",path=~\"$path\"}[$Interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(matrix_batch_http_request_latency_count{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"$method\",path=~\"$path\",status_code!=\"200\"}[$Interval]))\n/ \nsum(rate(matrix_batch_http_request_latency_count{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"$method\",path=~\"$path\"}[$Interval]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "平均响应时间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(matrix_batch_http_request_latency_sum{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"$method\",path=~\"$path\",status_code=~\"$status\"}[$Interval])) \n/\nsum(rate(matrix_batch_http_request_latency_count{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"$method\",path=~\"$path\",status_code=~\"$status\"}[$Interval]))",
     "legendFormat": "ResponseTime"
    }
   ]
  },
  {
   "title": "慢请求统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "慢请求明细表",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sum(increase((matrix_batch_http_request_latency_bucket{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"$method\",path=~\"$path\",status_code=~\"$status\",le=\"+Inf\"}\n- ignoring(le)\nmatrix_batch_http_request_latency_bucket{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"$method\",path=~\"$path\",status_code=~\"$status\",le=\"50\"})[$__range:]) > 0)  by (cluster,method,path)"
      }
     ]
    }
   ]
  },
  {
   "title": "错误统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "错误请求分布",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(increase(matrix_batch_http_request_latency_count{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"$method\",path=~\"$path\",status_code=~\"4.*\"}[$__range:])) ",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(increase(matrix_batch_http_request_latency_count{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"$method\",path=~\"$path\",status_code=~\"5.*\"}[$__range:])) ",
       "legendFormat": "5xx"
      }
     ]
    },
    {
     "title": "错误请求明细表",
     "type": "table",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 17 },
     "targets": [
      {
       "expr": "sum(increase(matrix_batch_http_request_latency_count{job=~\"matrix-batch-metrics\",cluster=~\"$cluster\",instance=~\"$node\",method=~\"$method\",path=~\"$path\",status_code!=\"200\"}[$__range:]) > 0) by (cluster,method,path,status_code)"
      }
     ]
    }
   ]
  }
 ]
}