{
 "title": "Matrix - batch K8s层面监控",
 "description": "Matrix - batch K8s层面监控",
 "tags": [ "matrix-batch" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(k8s_batch_total_job_completed{job=\"matrix-batch-metrics\"}, exported_cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(k8s_batch_total_job_completed{job=\"matrix-batch-metrics\", exported_cluster =~\"$cluster\"}, namespace)"
   },
   {
    "name": "cronjob",
    "label": "cronjob",
    "query": "label_values(k8s_batch_total_job_completed{job=\"matrix-batch-metrics\", exported_cluster =~\"$cluster\", namespace=~\"$namespace\"}, cronjob)"
   },
   { "name": "Interval", "query": "1m,2m,10m,2h" }
  ]
 },
 "panels": [
  { "title": "总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running CronJob",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(k8s_batch_total_cronjob_running{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"})"
    }
   ]
  },
  {
   "title": "Suspend CronJob",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(k8s_batch_total_cronjob_suspend{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"})",
     "legendFormat": "Suspend"
    }
   ]
  },
  {
   "title": "Running Job",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(k8s_batch_total_job_running{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"})"
    }
   ]
  },
  {
   "title": "Completed Job",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(k8s_batch_total_job_completed{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"})"
    }
   ]
  },
  {
   "title": "Failed Job",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(k8s_batch_total_job_failed{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"})"
    }
   ]
  },
  {
   "title": "大数据任务 Running Job",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(k8s_batch_total_job_running{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"BIGDATA_TASK\"})",
     "legendFormat": "Bigdata"
    }
   ]
  },
  {
   "title": "CronJob 分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(k8s_batch_total_cronjob_suspend{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"})",
     "legendFormat": "Suspend"
    },
    {
     "expr": "sum(k8s_batch_total_cronjob_running{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"})",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Job 分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(k8s_batch_total_job_running{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(k8s_batch_total_job_completed{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"})",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(k8s_batch_total_job_failed{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"})",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "大数据任务 Job 分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(k8s_batch_total_job_running{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"BIGDATA_TASK\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(k8s_batch_total_job_completed{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"BIGDATA_TASK\"})",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(k8s_batch_total_job_failed{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"BIGDATA_TASK\"})",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "CronJob",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(k8s_batch_total_cronjob_running{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(k8s_batch_total_cronjob_suspend{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"})",
     "legendFormat": "Suspend"
    }
   ]
  },
  {
   "title": "Job",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(k8s_batch_total_job_running{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(k8s_batch_total_job_completed{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"})",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(k8s_batch_total_job_failed{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"})",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "大数据任务 Job",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(k8s_batch_total_job_running{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"BIGDATA_TASK\"})",
     "legendFormat": "Running Job"
    },
    {
     "expr": "sum(k8s_batch_total_job_completed{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"BIGDATA_TASK\"})",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(k8s_batch_total_job_failed{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"BIGDATA_TASK\"})",
     "legendFormat": "Failed"
    }
   ]
  },
  { "title": "资源消耗", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Running Job Request CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(k8s_batch_running_job_req_cpu{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"})"
    }
   ]
  },
  {
   "title": "Running Job Limit CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(k8s_batch_running_job_limit_cpu{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"})"
    }
   ]
  },
  {
   "title": "Running Job Request Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 18 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(k8s_batch_running_job_req_mem{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"})"
    }
   ]
  },
  {
   "title": "Running Job Limit Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 18 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(k8s_batch_running_job_limit_mem{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"})"
    }
   ]
  },
  {
   "title": "Running Job CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(k8s_batch_running_job_req_cpu{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"})",
     "legendFormat": "Req"
    },
    {
     "expr": "sum(k8s_batch_running_job_limit_cpu{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Running Job Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(k8s_batch_running_job_req_mem{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"})",
     "legendFormat": "Req"
    },
    {
     "expr": "sum(k8s_batch_running_job_limit_mem{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  { "title": "定时任务", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Running CronJob 创建时间分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(k8s_batch_running_cronjob_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"86400\"} > 0 )",
     "legendFormat": "< 1d"
    },
    {
     "expr": "count(k8s_batch_running_cronjob_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"259200\"} \n- ignoring(le) k8s_batch_running_cronjob_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"86400\"} != 0)",
     "legendFormat": "1d ~ 3d"
    },
    {
     "expr": "count(k8s_batch_running_cronjob_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"604800\"}\n- ignoring(le) k8s_batch_running_cronjob_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"259200\"} != 0)",
     "legendFormat": "3d ~ 7d"
    },
    {
     "expr": "count(k8s_batch_running_cronjob_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"1.296e+06\"}\n- ignoring(le) k8s_batch_running_cronjob_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"604800\"} != 0)",
     "legendFormat": "7d ~ 15d"
    },
    {
     "expr": "count(k8s_batch_running_cronjob_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"2.592e+06\"}\n- ignoring(le) k8s_batch_running_cronjob_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"1.296e+06\"} != 0)",
     "legendFormat": "15d ~ 30d"
    },
    {
     "expr": "count(k8s_batch_running_cronjob_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"+Inf\"}\n- ignoring(le) k8s_batch_running_cronjob_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"2.592e+06\"} != 0)",
     "legendFormat": "> 30d"
    }
   ]
  },
  {
   "title": "Running Job 创建时间分布",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(k8s_batch_running_job_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"60\"})",
     "legendFormat": "< 1m"
    },
    {
     "expr": "count(k8s_batch_running_job_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"600\"} \n- k8s_batch_running_job_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"60\"} != 0)",
     "legendFormat": "1 ~ 10m"
    },
    {
     "expr": "count(k8s_batch_running_job_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"3600\"} \n- k8s_batch_running_job_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"60\"} != 0)",
     "legendFormat": "10 ~ 60m"
    },
    {
     "expr": "count(k8s_batch_running_job_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"21600\"} \n- k8s_batch_running_job_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"3600\"} != 0)",
     "legendFormat": "1 ~ 6h"
    },
    {
     "expr": "count(k8s_batch_running_job_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"43200\"} \n- k8s_batch_running_job_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"21600\"} != 0)",
     "legendFormat": "6 ~ 12h"
    },
    {
     "expr": "count(k8s_batch_running_job_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"86400\"} \n- k8s_batch_running_job_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"43200\"} != 0)",
     "legendFormat": "12~24h"
    },
    {
     "expr": "count(k8s_batch_running_job_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"+Inf\"} \n- k8s_batch_running_job_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"86400\"} != 0)",
     "legendFormat": ">24h"
    }
   ]
  },
  {
   "title": "Running CronJob 创建时间分布",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "count(k8s_batch_running_cronjob_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"86400\"} > 0) by (exported_cluster, namespace, cronjob)",
     "legendFormat": "< 1d"
    },
    {
     "expr": "count(k8s_batch_running_cronjob_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"259200\"} \n- ignoring(le) k8s_batch_running_cronjob_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"86400\"} != 0) by (exported_cluster, namespace, cronjob)",
     "legendFormat": "1 ~ 3d"
    },
    {
     "expr": "count(k8s_batch_running_cronjob_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"604800\"}\n- ignoring(le) k8s_batch_running_cronjob_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"259200\"} != 0) by (exported_cluster, namespace, cronjob)",
     "legendFormat": "3 ~ 7d"
    },
    {
     "expr": "count(k8s_batch_running_cronjob_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"1.296e+06\"}\n- ignoring(le) k8s_batch_running_cronjob_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"604800\"} != 0) by (exported_cluster, namespace, cronjob)",
     "legendFormat": "7 ~ 15d"
    },
    {
     "expr": "count(k8s_batch_running_cronjob_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"2.592e+06\"}\n- ignoring(le) k8s_batch_running_cronjob_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"1.296e+06\"} != 0) by (exported_cluster, namespace, cronjob)",
     "legendFormat": "15 ~ 30d"
    },
    {
     "expr": "count(k8s_batch_running_cronjob_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"+Inf\"}\n- ignoring(le) k8s_batch_running_cronjob_starttime_bucket{job=~\"matrix-batch-metrics\",instance=~\"192.168.199.36:28899|192.168.130.133:28899|10.10.32.205:28899\",exported_cluster=~\"$cluster\",namespace=~\"$namespace\",cronjob=~\"$cronjob\",le=\"2.592e+06\"} != 0) by (exported_cluster, namespace, cronjob)",
     "legendFormat": "> 30d"
    }
   ]
  }
 ]
}